version: '3.9'

services:

  database:
    image: 'mirror.gcr.io/library/postgres:15-alpine'
    container_name: 'graduate-db'
    environment:
      - POSTGRES_USER=Stey
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=jenjetsu
    ports:
      - 15432:5432

  my-app:
    build:
      context: ./build
      dockerfile: graduate.dockerfile
    container_name: my-graduate-project
    environment:
      - DB_URL=jdbc:postgresql://npcb-database:5432/jenjetsu
      - DB_USER=Stey
      - DB_PASS=123321
    ports:
      - 10080:10080